area/ci:
  - ".github/**/*"
area/docs:
  - "site/**/*"
area/site:
  - "site/**/*"  
component/components:
  - "/src/custom/**/*"
component/icons:
  - "/src/icons/**/*"
framework/storyboard:
  - "packages/design-system/**/*"
