name: Slack Notify
on: 
  watch:
    types: [started]
  issues:
    types: [labeled] # Triggers when a label is added to an issue

jobs:
  star-notify:
    if: github.event_name == 'watch'
    name: Notify Slack on Star
    runs-on: ubuntu-latest
    steps:
      - name: Get current star count
        run: |
          echo "STARS=$(curl --silent 'https://api.github.com/repos/${{ github.repository }}' -H 'Accept: application/vnd.github.preview' | jq '.stargazers_count')" >> $GITHUB_ENV
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: rtCamp/action-slack-notify@v2
        with:
          args: '{"channel":"CSK7N9TGX","text":"${{ github.actor }} just starred ${{ github.repository }}! (https://github.com/${{ github.repository }}/stargazers) Total ⭐️: ${{ env.STARS }}"}'

  good-first-issue-notify:
    if: github.event_name == 'issues' && (github.event.label.name == 'good first issue' || github.event.label.name == 'first-timers-only')
    name: Notify Slack for Good First Issue
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: rtCamp/action-slack-notify@v2
        with:
          args: '{"channel":"C019426UBNY","text":"A good first issue label was just added to ${{ github.event.issue.html_url }}."}'
